---
title: "Soziale Netzwerke in Fußbalteams - Der Schlüssel zum Erfolg?"
author: "Jakob Berg"
date: "`r lubridate::today()`"
output:
  word_document: default
  html_document: default
---

# 1. Die Bundesligasaison 2019/20: Spannendes oder erwartbares Saisonfinale? 

An einem verregneten Dienstag im Juni wurde der FC Bayern mit einem unspektakulären 1:0 gegen Werder Bremen erneut Deutscher Fußball-Meister. Umso spektakulärer ist, dass der Erfolgsklub aus dem Süden die Bundesliga bereits das achte Mal in Folge gewinnen konnte. Sicher fußt diese Dominanz auch auf finanzielle und vor allem sportliche Überlegenheit. Auch in den beiden direkten Duellen gegen den späteren Bundesliga-Zweiten und aktuell größten Konkurrenten, Borussia Dortmund, konnte sich der Rekordmeister aus München deutlich abheben und lies den Borussen mit einem spielübergreifenden 5:0 keine Chance. Doch haben die Bayern wirklich einfach nur die besseren Spieler, die ausgereiftere Taktik und die überlegerene Mentalität? Oder beruht das oft zitierte 'Siegergen' des FCB auch auf anderen Faktoren? Diese Analyse beschäftigt sich mit den gruppenpsychologischen Aspekten des Sports und untersucht hierzu die sozialen Netzwerke in Fußballmannschaften, exemplarisch bei Borussia Dortmund und dem FC Bayern München. Ähnlich wie beim bekannten Spielmodus Ultimate Team (UT) des Fußballvideospiels FIFA, herausgegeben vom Branchenprimus EA-Sports, werden die Beziehungen der Spieler, die gemeinsam auf dem Feld stehen, untersucht und bewertet. Bei FIFA UT wird dieses Bewertungssystem Teamchemie genannt und trägt erheblich zur Spielstärke oder -schwäche der erspielten Mannschaften bei. Im Rahmen dieser Analyse werden die Netzwerke, die die beiden Teams anhand von Verbindungsattributen wie Sprache oder gemeinsame Nationalität darstellen, anhand von zwei Forschungsfragen untersucht:  
  1. Sind Mannschaften mit enger verbundenen Netzwerken sportlich erfolgreicher?    
  2. Sind Spieler die in ihren Teams enger vernetzt sind, sportlich erfolgreicher?  
Diese Fragen werden durch Bewertungs- und Analyseeinheiten aus der Netzwerkanalyse und Spielerbewertungen von der Sportzeitung Kicker und dem Sport-Statistiktool Sofascore analysiert. Zunächst wird aber theoretisch die Bedeutung von Gruppenpsychologie und sozialen Beziehungen im Sport erörtert, um dann analytisch die Netzwerke der beiden Teams zu untersuchen. 

vllt. noch bissl LR reinbringen anhand S.224 Lau

# 2. Sozialpsychologie und Gruppendynamik im Profifußball

In der Sportwissenschaft und der Sportpsychologie spielen Gruppen, Teams und deren Dynamiken sowie sozialen Strukturen eine elementare Rolle. Gruppen haben einen erheblichen psychosozialen Einfluss auf Athleten und Sportler als Teil der Sportgruppe (vgl.: Lau & Plessner 2016: 180). Im wissenschaftlichen Diskurs gibt es eine pessimistische und eine optimistische Auffassung über den Einfluss von Gruppendynamiken auf die sportliche Leistung von Teams und Einzelsportlern. Während einerseits davon ausgegangen wird, dass es durch die verschiedenen Vorgänge einer Gruppendynamik zu gewissen Prozess-, Kommunikations- und Motivationsverlusten kommt, wird andererseits angenommmen, dass durch gemeinsame Motivations- und Lernprozesse die Einzelleistung verbessert werden kann. Das Konzept hinter der pessimistischen Auffassung wird Prozessverlust genannt, die beschriebene mögliche positive Auswirkung Synergieeffekt (vgl.: Lau & Plessner 2016: 180). Im Rahmen dieser Analyse wird von letzterem ausgegangen und erwartet, dass engere soziale Netzwerke in Fußballteams sowohl beim gesamten Team als auch bei den einzelnen Spielern bessere sportliche Leistungen initieren können. Voraussetzung hierfür ist aber die sportwissenschaftliche Theorie der erfolgreichen Gruppenkohäsion innerhalb der Teams. 
Konkret meint dies den Prozess einer Gruppe, die sich langfristig zusammen schließt um sowohl gemeinsame Ziele als auch Zufriedenheit für alle Gruppenteile zu erreichen (vgl.: Lau & Plessner 2016: 215). Der Erfolg einer Gruppenkohäsion fußt auf vier Faktoren, aus denen die Variablen der nachfolgenden Netzwerk-Analyse erarbeitet wurde. Im Einzelnen sind dies situative und persönliche sowie Führungs- und Mannschaftsfaktoren. Für diese Untersuchung sind vor allem die ersten beiden relevant. Als situative Faktoren sind gesellschaftliche und kulturelle Strukturen und geografische Voraussetzungen von Bedeutung (vgl: Lau & Plessner 2016: 219). So werden die Netzwerke nachfolgend auf Sprache und Natationalität untersucht. Außerdem sind die theoretisch formulierten persönlichen Faktoren in den Netzwerken von Bedeutung. Eigenschaften wie Alter und Geschlecht haben Einfluss auf das Zusammenwirken einer Gruppe. Selbstverständlich werden im Rahmen dieser Analyse nur Männerteams untersucht, weswegen nur die verschiedenen Altersgruppen eines Teams als maßgebende Netzwerkvariablen beleuchtet wurden. Nicht zuletzt beieinflussen auch mannschaftsbezogene Faktoren die Kohäsion, als Beispiele dienen hier die Dauer der gemeinsamen Teamzugehörigkeit der Mitglieder und kollektive Gruppenerinnerungen wie bedeutende gemeinsame Erfolge oder Niederlagen. Deswegen wurden gemeinsame Mitgliedschaften in Nationalmannschaften sowie Erfolge in der Championsleague und einer Weltmeisterschaft berücksichtigt (vgl: Lau & Plessner 2016: 218ff). 
Ein Zusammenhang von Kohäsion und sportlicher Leistung wurde zwar theoretisch immer wieder erörtert und scheint auch kohärent, allerdings konnte in den wenigen bekannten Untersuchungen die sich mit dieser Fragestellung befassen, bisher nur ein mäßiger statistischer Zusammenhang aufgezeigt werden können (vgl: Lau & Plessner 2016: 225) Aus diesem Grund wird die Fragestellung im Folgenden anhand einer Netzwerkanalyse untersucht, um so mögliche neue Erkenntnisse der Auswirkung von sozialen Beziehungen in Sportteams gewinnen zu können. Zunächst wird aber kurz das methodische Vorgehen und das verwendete Forschungsdesign erläutert

- Alfermann: vorheriger Erfolg hat Einfluss auf Kohäsion (eher als andersrum, durch Studien nachgewiesen) 241

# 3. Methodik und Forschungsdesign

- Welche Variablen, Spieler, Zeitraum verwendet
- beschreiben dass dann als Regression verwendet
- Kurzfassung abgleichen mit Powner Reasearch Design

# 4. FC Bayern und Dortmund: Soziale Gruppendynamik als Siegfaktor? 
- Dichte (FCB: 0,93; BVB: 0,82)  

# 5. Schluss/Fazit

mehr interne Informationen wären sinnvoll, Freundschaft, Streit --Kohäsionsdiagnostik
Trainerposition könnte auch beleuchtet werden

